# Generated by Django 3.0.4 on 2020-05-03 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Producers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('content', models.TextField(max_length=100)),
                ('link', models.URLField()),
                ('producer_id', models.ForeignKey(db_column='Producer_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='Producers.Producers')),
            ],
        ),
    ]
