# Generated by Django 3.0.4 on 2020-05-03 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Producers', '0002_articles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'managed': False},
        ),
    ]
