# Generated by Django 3.0.4 on 2020-05-03 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Producers', '0003_auto_20200503_1256'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='articles',
            table='articles',
        ),
    ]
