# Generated by Django 3.0.4 on 2020-05-03 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Producers', '0004_auto_20200503_1301'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='articles',
            table='Articles',
        ),
    ]
